"""Update the offline holiday calendar from the Cabinet Office CSV."""
import csv
import io
from pathlib import Path
from urllib.request import urlopen

SOURCE_URL = "https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv"
OUTPUT = Path(__file__).resolve().parents[1] / "js/services/japanese-holidays.js"


def main():
    with urlopen(SOURCE_URL, timeout=30) as response:
        rows = list(csv.reader(io.StringIO(response.read().decode("cp932"))))[1:]
    dates_by_year = {}
    for row in rows:
        year, month, day = map(int, row[0].split("/"))
        dates_by_year.setdefault(year, []).append(f"{month:02d}-{day:02d}")
    years = sorted(dates_by_year)
    if years != list(range(years[0], years[-1] + 1)):
        raise ValueError("Holiday calendar has missing years")
    lines = [
        "// Generated by scripts/update-japanese-holidays.py. Do not edit directly.",
        f"// Source: Cabinet Office, {SOURCE_URL}",
        "// Includes substitute holidays and holidays between national holidays.",
        f"export const HOLIDAY_FIRST_YEAR = {years[0]};",
        f"export const HOLIDAY_LAST_YEAR = {years[-1]};",
        "const datesByYear = {",
    ]
    lines.extend(f'  {year}: "{",".join(dates_by_year[year])}",' for year in years)
    lines.extend([
        "};",
        "export const JAPANESE_HOLIDAYS = new Set(",
        '  Object.entries(datesByYear).flatMap(([year, dates]) => dates.split(",").map((date) => `${year}-${date}`))',
        ");",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Updated {OUTPUT.name}: {years[0]}-{years[-1]}, {len(rows)} holidays")


if __name__ == "__main__":
    main()
